name: Deploy to github pages

on:
  push:
    branches: [main]

permissions: 
  pages: write
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Setup nodejs
        uses: actions/setup-node@v4
        with: 
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Build Project
        run: npm run build && npm run export
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          publish_branch: gh-pages
          force_orphan: true
